### ISSUE TITLE
Rendezvous IGD port timeout should be configurable/disableable

### ISSUE THREAD

**Issue by canndrew** [ustulation/p2p#24]
Rather than always set to 5min. It's possible (?) that some routers might kill a connection if the port expires while there's an active connection on it. We should investigate whether this fear is justified and whether we need to make it so the timeout can be disabled.

**Comment by povilasb** [comment]
IGD use in this crate will be removed completely. We want  `p2p` to be solely responsible for hole punching. That will make crate a lot more simple and easier to maintain.

**Comment by ustulation** [comment]
No longer relevant
