### ISSUE TITLE
bincode version not valid

### ISSUE THREAD

**Issue by shnupta** [ustulation/p2p#6]
When building with p2p as a dependency I get this error:

```
error: no matching version `~1.0.0-alpha6` found for package `bincode` (required by `p2p`)
location searched: registry https://github.com/rust-lang/crates.io-index
versions found: 0.8.0, 0.7.0, 0.6.1, ...
```

**Comment by ustulation** [comment]
@shnupta : it's building fine for me (i use linux so the CI is currently set only for linux & OSX (travis) builds and shows everything's green too as you can see).

Also bincode is `~0.8.0` [as here](https://github.com/ustulation/p2p/blob/12b4851b0d6cf4e543bd5d1ede01f40af56b30a3/Cargo.toml#L13) which is valid AFAIK.

Can you pls investigate a bit more and also see if it's not something to do with your end ? Thanks.

**Comment by shnupta** [comment]
@ustulation : yeah the build looks fine and I've checked the Cargo.toml but if you look on crates.io: https://crates.io/crates/p2p

Under dependencies it says it requires bincode ~1.0.0-alpha6, which has been yanked from crates.io so is no longer available. I'm pretty sure there is nothing I can do on my end. Does the version on crates match the repository? (crates says it was last updated 3 months ago but I see some changes were made to the repository 2 months ago)

**Comment by ustulation** [comment]
@shnupta Ah the one in the crates, indeed. I forgot to cargo publish the changes it seems. Should be done now.
