### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by mboogerd** [ustulation/p2p#68]
I'm interested in using this library in my Apache licensed code, however I understand that this license is only one way [compatibility](https://www.apache.org/licenses/GPL-compatibility.html) with your GPL. Could you help me understand if there is any way in which I can use your code in my Apache licensed code?

**Comment by ustulation** [comment]
@mboogerd ah nw, i'll change it to MIT soon and do a cargo-publish. Thanks !

**Comment by mboogerd** [comment]
That's awesome, thanks a bunch! 👍
